//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mebel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MebelDB : DbContext
    {
        public MebelDB()
            : base("name=MebelDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ChooseSize> ChooseSizes { get; set; }
        public virtual DbSet<LanguageTB> LanguageTBs { get; set; }
        public virtual DbSet<Maifacturer> Maifacturers { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<OurStory> OurStories { get; set; }
        public virtual DbSet<ProductImage> ProductImages { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<section1Divs> section1Divs { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
    }
}
