//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mebel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductImages = new HashSet<ProductImage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<byte> Discount { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> MaifacturerId { get; set; }
        public Nullable<byte> Available { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public string color { get; set; }
        public string Size { get; set; }
        public string Description { get; set; }
        public Nullable<int> LanguageId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual LanguageTB LanguageTB { get; set; }
        public virtual Maifacturer Maifacturer { get; set; }
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
    }
}
